apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    app: flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: flaskapp
        image: chinmayapradhan/flaskapp:1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: ""
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYAQL_DB
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
--- 
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec: 
  selector:
    app: flaskapp
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30007
