apiVersion: v1
kind: ConfigMap 
metadata:
  name: mysql-initdb-config
data: 
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;
    CREATE TABLE messages (id INT AUTO_INCREMENT PRIMARY KEY, message TEXT);


# docker ps
# docker exec -it <container_id> bash
# mysql -u root -p 
# show databases;
# use mydb;
